### ISSUE TITLE
Give weekends a style

### ISSUE THREAD

**Issue by nibblerrick** [BKeyport/MMM-Multimonth#10]
Hi,

I already mentioned in on the forum, but again: this is a great module, thank you very much!
Overall I am very happy and styling with some CSS is good to do.
However here is one featurerequest:
May it be possible that the weekends get some extra-style? E.g. make the font-weight lower or so. On the classic wallcalenders the weekends have most time a bit different style, too.
I haven't seen a css-class I could use for that, therefore I believe when the grid is generated the saturday and sunday-days would need to get an extra css-class.
If that's already possible now please give me a hint.

regards

   Nico

**Comment by BKeyport** [comment]
I will have to look into that. As of right now, it's doing a simple count through the weeks to account for internationalization. If I can figure out how to make it check to see if the day is a weekend day,  I'll do it. I'm rather busy at the moment, however, but I will get to it when I can.

**Comment by BKeyport** [comment]
Done, works in international mode. Will only highlight Saturday and Sunday. May adjust later to specify which days are weekend for intational 

added: 
to config.js:
```
highlightWeekend: [true|false], //defaults to false - will use .MMM-Multimonth .weekend if true. 
```

to css: .MMM-Multimonth .weekend  - refer to CSS for code.

**Comment by nibblerrick** [comment]
Okay.... I wanted to say thanks that you consider it and thought maybe in half a year or so something could be there.
That was fast! Thank you very much, works perfect!
Over here we have the weekenddays saturday and sunday, so for me it's fine.
Only as I have at the moment the backgroundcolor for the current day same as the normal days my saturday is now the wrong color, but that's easy to fix with a little bit makeover. Or maybe that could also work with css-variables which I wanted to look at some time and now have a reason to do so.

So thank you very very much again for that fast new feature, I really wouldn't have thought this would be done so fast.

**Comment by BKeyport** [comment]
as of typing this, Today is the 9th of January, which should be highlighting different than the rest of the weekend days. Is that what you're talking about?

**Comment by nibblerrick** [comment]
Yes, see the screenshot.
![chrome_2021-01-09_22-43-53](https://user-images.githubusercontent.com/20553366/104109250-4c30ba80-52cc-11eb-87a9-64a22f68d754.png)
Looking at it and checking I haven't even the same color, normal days I have a lighter gray and the actual day in white...
I thought I had the actual day styled like the other normal days.
At the moment it looks a bit odd for the "actual weekend day" but that's simply a stylingthing, I think.
If the color for the actual day could be the color of the normal styling for the day (so normal days on days and weekendstyle on weekend) could be nice, too if I just want to highlight the actual day with a border, mimicking more the style of an "offline" wallcalendar.
But as said, I am very happy with it and changing the styling a bit now is an easy thing to make the actual day look fine with the new weekendstyle.

**Comment by BKeyport** [comment]
Yes, that's exactly as intended. The current day will always pick up the "current_day" css, otherwise it's "day" or "weekend" depending.

**Comment by nibblerrick** [comment]
That's fine, thanks again very much!

**Comment by nibblerrick** [comment]
Just saw the current-day-weekend-class. Wow! Perfect!

**Comment by nibblerrick** [comment]
I styled the calendar a bit. I removed the padding most times and added a border to have a consistent look when drawing a border on the current day. 

My CSS (I used the original CSS to have all values and if the original changes I have all values in the custom css)
```
.MMM-Multimonth .calendar {
  display: flex;
  align-items: stretch;
  white-space: nowrap;
  border: 0;
  font-size: 30px;
  line-height: 34px;
  column-gap: 30px;
}

.MMM-Multimonth .month {
  flex-basis: 100%;
  padding: 0px;
  display: flex;
  flex-direction: column;
}

.MMM-Multimonth .month-header {
  background-color: blue;
  color: white;
  font-size: 36px;
  line-height: 40px;
  border-radius: 10px;
}

.MMM-Multimonth .days-header {
  display: flex;
  flex-direction: row;
  align-items: stretch;
}

.MMM-Multimonth .day-header {
  color: white;
  flex: 1 1 0px;
  min-width: 0;
  padding-left: 0px;
  padding-right: 0px;
  border: 4px solid transparent;
}

.MMM-Multimonth .week {
  display: flex;
  flex-direction: row;
  align-items: stretch;
  padding-top: 5px;
}

.MMM-Multimonth .weeknumber {
  flex: 1 1 0px;
  min-width: 0;
  padding-left: 0px;
  padding-right: 0px;
  border-radius: 8px;
  background-color: DarkGrey;
  color: black;
  border: 4px solid transparent;
}

.MMM-Multimonth .day {
  flex: 1 1 0px;
  min-width: 0;
  padding-left: 0px;
  padding-right: 0px;
  color: gainsboro;
  border: 4px solid transparent;
}

.MMM-Multimonth .weekend {
  flex: 1 1 0px;
  min-width: 0;
  padding-left: 0px;
  padding-right: 0px;
  border-radius: 8px;
  background: none;
  color: rgba(255, 0, 0, 0.534);
  border: 4px solid transparent;
}

.MMM-Multimonth .current_day {
  flex: 1 1 0px;
  min-width: 0;
  padding-left: 0px;
  padding-right: 0px;
  background: none;
  border-radius: 8px;
  color: white;
  background: none;
  border: 4px solid yellow;
}

.MMM-Multimonth .current_day_weekend {
  flex: 1 1 0px;
  min-width: 0;
  padding-left: 0px;
  padding-right: 0px;
  border-radius: 8px;
  color: black;
  background: none;
  border: 4px solid yellow;
  color: rgba(255, 0, 0, 0.829);
}

.MMM-Multimonth .daydim {
  flex: 1 1 0px;
  min-width: 0;
  padding-left: 0px;
  padding-right: 0px;
  color: grey;
  border: 4px solid transparent;
}
```

The only thing I am unsure at the moment is if the darkgrey background is to big on the weeknumbers as it fill the transparend border, too. But that's simply a stylingthing I have to look if it bothers me after some days :-)

Thanks again, couldn't be happier with the result and maybe the border-styling-css is interesting to you or someone else.

![image](https://user-images.githubusercontent.com/20553366/104124350-c571f100-5350-11eb-93b8-9fe08243f96c.png)
