### ISSUE TITLE
Define start of the week (i.e., Monday or Sunday)

### ISSUE THREAD

**Issue by ebonak** [BKeyport/MMM-Multimonth#12]
Suggestion: Would it be possible to define the start of the week on Monday (ie. first day of week, rather than Sunday)?

(Can I attach the "enhancement" label here? - if so, I don't see it)

**Comment by BKeyport** [comment]
Start of week is defined by the language used as of this time. I've been looking at other solutions, however, I've been busy with other projects that actually earn me a paycheck (That evil W word)

**Comment by BKeyport** [comment]
See #1

**Comment by ebonak** [comment]
> Start of week is defined by the language used as of this time. 

Does this refer to the Javascript API that provides calendar functions?  I don't know much JS and I'm new to MM  and its modules, but I'm trying to get more comfortable with the setup (and github in the process).

> I've been looking at other solutions, however, I've been busy with other projects that actually earn me a paycheck (That evil W word)

No worries, I totally understand about priorities, but perhaps this could find itself on a to-do list for future enhancements. It's certainly not urgent at all. Thanks for the reply.

**Comment by BKeyport** [comment]
Sorry, I should have been more clear. The language as set by MagicMirror.  So, if you switched to french, moment.js tells me monday is the first day of the week, and my module reacts accordingly. from MagicMirror's config.js 

```
var config = {
...
    language: "en",
...
```
  
 it's on the list.

**Comment by ebonak** [comment]
> Sorry, I should have been more clear. The language as set by MagicMirror. So, if you switched to french, moment.js tells me monday is the first day of the week, and my module reacts accordingly. from MagicMirror's config.js
> 
> ```
> var config = {
> ...
>     language: "en",
> ...
> ```
> 
> it's on the list.

Ah .. ok, cool, thanks, so looks a bit like a locale/cultural setting. I'll have to learn about all the various setup/config files MM uses/requires for developers - this gives me some idea. I appreciate learning about this.

**Comment by BKeyport** [comment]
This was literally my first time with javascript and css. I built it for my need, and it became useful for others, so I used the easiest way to make things work. Can't blame me for being lazy on a free job, eh? ;)

**Comment by ebonak** [comment]
> This was literally my first time with javascript and css. I built it for my need, and it became useful for others, so I used the easiest way to make things work. Can't blame me for being lazy on a free job, eh? ;)

Nope .. and this is the best way to learn (to work on something relevant to yourself). I picked up C# similarly writing a Windows app I wanted.

**Comment by BKeyport** [comment]
Hey, all. Sorry about the _long_ delay, however, getting inspired by MMRize's CalExt3 project, I've finally done this! See new startWeek config option!
