### ISSUE TITLE
weekNumbers: true makes "UNDEFINED" output

### ISSUE THREAD

**Issue by nibblerrick** [BKeyport/MMM-Multimonth#16]
Hi!

First of all thanks for maintaining the module!

I just updated MM and the modules, put the new options in but only got `UNDEFINED` shown at the modules position.
First I looked in the developer tools to see if my CSS has hidden something, but there wasn't anything in the site-source besides the `UNDEFINED`.
So I disabled all options and tried to enable one by one. As soon as I enable the weeknumbers it turns from showing the calendar to `UNDEFINED`.
Below is the current working config.
If you could look into that at some point it would be nice.

```
                {
                        module: 'MMM-Multimonth',
                        position: 'top_bar',
                        config: {
                                startMonth: -1,
                                monthCount: 3,
                                monthsVertical: false,
                                highlightWeekend: true,
                                repeatWeekdaysVertical: true,
//                              weekNumbers: true,
                                startWeek: 1,
                                headerType: 'short'
                        }
                },
```

Thanks again for the module!

**Comment by BKeyport** [comment]
indeed, I'll get to it this afternoon my time. I'll have a solution by the
end of my day.

**Comment by nibblerrick** [comment]
No need to hurry, thanks in advance!

**Comment by BKeyport** [comment]
Solved. Serves me right for working in a fiddle to generate code, and forgetting to update a variable to MM's style... 🙃

**Comment by nibblerrick** [comment]
Thank you! That was quick :-)
