### ISSUE TITLE
ISO 8601 Week number

### ISSUE THREAD

**Issue by iks82** [BKeyport/MMM-Multimonth#19]
The ISO 8601 standard defines week numbers using a Monday-based week (i.e. the week begins on Monday). Under this definition, the first week of the year is determined to be the first week that contains a Wednesday.

This means, then the calculation of the week number has to base on January 4th.  
So the code should look like

```
const weekNumber = (dateObject) => {
	var fourJan = new Date(dateObject.getFullYear(),0,4);
	var numberOfDays = Math.floor((dateObject - fourJan) / (24 * 60 * 60 * 1000));
	var result = Math.ceil(( date.getDay() + 1 + numberOfDays) / 7);
	return result;
}
```

**Comment by BKeyport** [comment]
the bug is actually bigger than that, but thanks for letting me know about the ISO week - I was wondering what the difference is. It appears from what I can see by moving the calendar around, it's calculating the correct START, but not the correct END as is. 

I'll be working on it and have an answer soon. Tentatively, there will be a new sub-option that uses ISO week. 
```
weekNumbers: false, // Whether to display the week numbers in front of each week.
weekNumbersISO: false, // Use ISO (monday based week) rather than US (Sunday Based week) Ignored if weekNumbers is not used. 
```

**Comment by BKeyport** [comment]
I've changed your idea on how to fix it and adjusted according to these rules: 

The ISO week numbering standard are based on these rules:

- An ISO week will always have seven days that can contain days from the current month as well as the next month. This is true of days that overlap from the last and first months of the year.
- A week cannot be broken; there are no partial weeks that contain only four or five days.
- The ISO week always starts on Monday and ends on Sunday.

Following the American standard, these rules apply:

- A week starts on Sunday and can have less than seven days in that week. This is called a partial week.
- A week can begin on a day other than a Sunday, although Sunday is considered the first day of the calendar week. However, a week that starts in the middle will behave as though part of the same week number as it's predecessor week.
- Another point about the US partial week standard is that the week containing January 1st is always reflected as the first week of the next year. This case is true even if the first day begins in the middle of the week.

**Comment by BKeyport** [comment]
Appears to be fixed. Let me know if anything is wrong. Thanks for the report.

**Comment by iks82** [comment]
Yes, it looks good!
Thnak you!
