### ISSUE TITLE
Day highlight doesn't update

### ISSUE THREAD

**Issue by tgtechy** [BKeyport/MMM-Multimonth#26]
Hi and thanks for your excellent work - this is my favorite calendar module for the MagicMirror!

I noticed that the highlighted day doesn't update for me.  See picture.  The 'native' MagicMirror clock module updates fine and is shown in center of the display.  The MMM-Multimonth module is on the left and you will notice the day is behind by one day.   When rebooted, it highlights the correct day.
![20240807_083158](https://github.com/user-attachments/assets/afd1b266-1d1f-4615-be32-ea3a4d426c07)

My configuration:

MagicMirror Version 2.28.0, Raspberry Pi 3 Model B Plus Rev 1.3

Linux version 6.1.21-v8+ (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1642 

Local time is US/Eastern Time Zone

```


{       
                module: 'MMM-Multimonth',
               position: 'top_left', // can be any of the positions
               config: {
                           startMonth:0,
                           monthCount:2,
        }
},
```

**Comment by BKeyport** [comment]
Indeed. Somehow I broke the midnight update. I'll fix it up when I have a moment. 

As a temporary solution, if you use the default "calendar" module at all, even undisplayed, it will send out regular notifications that will trigger my module to update when it does. Feel free to use this stub in your config.js to trigger the update. 

You would see underlines on Saturday then Sunday for it, however, you can turn those off with ```eventsOn: False,``` in my code. 


```
		{
			module: "calendar", // Built in
			// (hidden) position: "top_center", 
			config: {
				animationSpeed: 0,
				broadcastEvents: true,
				broadcastPastEvents: true,
				fetchInterval: 60000, // minimum 1 minute. 
				maximumEntries: 99,
				calendars: [
					{
						url: "https://www.seahawks.com/api/addToCalendar/ag/d?text=Seattle+Seahawks+Games",
						name: "Seahawks",
						symbol: "football",
						color: "#69BE28",
					},
				],
			},
		},

```

**Comment by BKeyport** [comment]
As of this point, I cannot find anything wrong with the code, nor can I find any help that won't talk to me like I'm a total idiot. 

I'm looking into it, but it don't make sense why it don't work.

**Comment by tgtechy** [comment]
Hi again -
No worries!
I am not a javascript expert, but have some experience in C++ and
microcontroller programming.
I have had some problems with other MagicMirror calendar modules not
updating the day properly and they also seem to implement workarounds and
have issues with the DOM updating.
I did a little looking into this and it seems there must be some generic
issue with the MagicMirror software allowing modules to implement timers
and date/time functions in realtime.
Best wishes!

**Comment by BKeyport** [comment]
I think the issue was mine. I misunderstood how the module flows, from what I can tell - it upset me to the point of doing more research. 

I think I have it solved - however, I'm getting confirmation from the folks that work the main code that it's as good as it can be, if so, solution will be posted.

**Comment by BKeyport** [comment]
Fixed, at least for now. May adjust later if I learn better method.
