### ISSUE TITLE
Won't initialize upon 1st run unless Calendar module is also loaded

### ISSUE THREAD

**Issue by tgtechy** [BKeyport/MMM-Multimonth#27]
The MMM-Multimonth module displays as "UNDEFINED" unless the MagicMirror Calendar module is also loaded.  Maybe your recent fix to update at midnight affected this.  I'm guessing you may need to call your initialization function when the module is loaded the first time.

Also, in line 6 of MMM-Multimonth.css, you have a space in the designator "--color-ba ckground"  ... it may affect the CSS?

**Comment by BKeyport** [comment]
Thanks. Yeah, it’s. Likely the temporary update routine. I’ll look into it shortly Sent from my iPhoneOn Aug 19, 2024, at 4:52 PM, tgtechy ***@***.***> wrote:﻿
The MMM-Multimonth module displays as "UNDEFINED" unless the MagicMirror Calendar module is also loaded.  Maybe your recent fix to update at midnight affected this.  I'm guessing you may need to call your initialization function when the module is loaded the first time.
Also, in line 6 of MMM-Multimonth.css, you have a space in the designator "--color-ba ckground"  ... it may affect the CSS?

**Comment by BKeyport** [comment]
It appears that I forgot to put in some error checking, and it's puking because of that.

I'm Remote, and can't really code well on my laptop - it's too small of a screen. I'll get to it likely next weekend.

**Comment by dathbe** [comment]
switching to the `dev` branch is a quick short-term fix.  I'm not seeing any errors in my logs with the main branch, so I'm not sure what error checking we'd need to add...otherwise I'd give it a shot.

**Comment by BKeyport** [comment]
Dathbe: It's a variable being unused when there's no calendar going "undefined" - the dev branch is out of date, haven't used that in ages - last time it was used, I was doing a major rewrite. 

It's actually a rather easy fix, I just have to fix it when I'm at the office with my big screens.

**Comment by dathbe** [comment]
> the dev branch is out of date, haven't used that in ages - last time it was used, I was doing a major rewrite.

It says it was updated 2 months ago and is only 4 commits behind.  In any event, it shows me a calendar that is more or less what I've customized on the main branch.  Better than "Undefined"!

**Comment by BKeyport** [comment]
Fixed. Uploading now.

**Comment by dathbe** [comment]
Wow.  Quick turnaround.  Thanks!  And thanks for a great module.

**Comment by BKeyport** [comment]
I knew what was wrong, I just can't deal with the lack of screen space when I'm mobile.. I'm spoiled by an 32x9 screen at work. :)

**Comment by tgtechy** [comment]
Thank you too for a great module!
