### ISSUE TITLE
Beginning is posponed

### ISSUE THREAD

**Issue by TheGardener88** [BKeyport/MMM-Multimonth#3]
Hey it is a really nice module !

But everytime my three months look always like your screenshot.
September starts on thursday and so on...
this needs to be fixed. And then its perfect.
Keep it up

**Comment by BKeyport** [comment]
I'm not quite sure what you're saying here. Can you send me a screenshot?

**Comment by TheGardener88** [comment]
![20200909_164305](https://user-images.githubusercontent.com/39694079/92614149-016e4a00-f2bc-11ea-87d7-5bd9e65232f5.jpg)

I hope u can see my screenshot. Everything is in german but September 9th should be a Wednesday not Friday

**Comment by TheGardener88** [comment]
it would also be really good if you could insert the calendar week on the left

**Comment by BKeyport** [comment]
ok - I see what you're referring to. Not sure if it's a bug with my side or the moment module. 

Can I see your config.js and know what country your Pi is set to? 

Thanks! 

As for the second item, I'd be able to insert that, I think. Should be easy to do. I'll add that to the list.

**Comment by BKeyport** [comment]
I'm working on it. Having trouble with my own mirror changing languages. Will get back to you soon. I *think* the problem is within the moment.js, however.

**Comment by TheGardener88** [comment]
language: "de",
timeformat: 24,
units: "metric",
the other data have not been changed

**Comment by BKeyport** [comment]
FYI, I crashed my mirror, and am rebuilding it, and stupid me didn't backup the configs. :(

I'll get to debugging again in a bit.

**Comment by BKeyport** [comment]
I believe I have it fixed. It now moves as it should. Please double check and let me know.

**Comment by BKeyport** [comment]
go to https://github.com/BKeyport/MMM-Multimonth/issues/4 for progress on your request.

**Comment by TheGardener88** [comment]
well done !
